version: "3.9"

services:
  zookeeper:
    image: zookeeper:3.8.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:3.28.0
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka

  order-service:
    image: golang:1.24
    container_name: order-service
    working_dir: /app
    volumes:
      - ./order-service:/app/order-service   # mapa seu binário local
    command: ["./order-service"]
    depends_on:
      - kafka

  notification-service:
    image: golang:1.24
    container_name: notification-service
    working_dir: /app
    volumes:
      - ./notification-service:/app/notification-service  # mapa seu binário local
    command: ["./notification-service"]
    depends_on:
      - kafka
